// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rey.EQueue.EF;

#nullable disable

namespace Rey.EQueue.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230406143514_AddFKToTimetable")]
    partial class AddFKToTimetable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Rey.EQueue.Core.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimetableId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("ClassId");

                    b.HasIndex("TimetableId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.Queue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ScheduledClassId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("QueueId");

                    b.HasIndex("ScheduledClassId");

                    b.ToTable("Queues");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PrevRecordId")
                        .HasColumnType("int");

                    b.Property<int>("QueueId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("RecordId");

                    b.HasIndex("QueueId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.ScheduledClass", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubjectInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("ScheduledClassId");

                    b.ToTable("ScheduledClasses");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.SubjectInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("SubjectInstanceId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectInstances");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.SubjectInstanceTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("SubjectInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("SubjectInstanceTeacherId");

                    b.HasIndex("SubjectInstanceId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SubjectInstancesTeachers");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.Timetable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AppliedPeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AppliedPeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubjectInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("TimetableId");

                    b.HasIndex("SubjectInstanceId");

                    b.ToTable("Timetables");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.Class", b =>
                {
                    b.HasOne("Rey.EQueue.Core.Entities.Timetable", "Timetable")
                        .WithMany("Classes")
                        .HasForeignKey("TimetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timetable");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.Queue", b =>
                {
                    b.HasOne("Rey.EQueue.Core.Entities.ScheduledClass", "ScheduledClass")
                        .WithMany("Queues")
                        .HasForeignKey("ScheduledClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledClass");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.Record", b =>
                {
                    b.HasOne("Rey.EQueue.Core.Entities.Queue", "Queue")
                        .WithMany("Records")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rey.EQueue.Core.Entities.User", null)
                        .WithMany("Records")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.ScheduledClass", b =>
                {
                    b.HasOne("Rey.EQueue.Core.Entities.SubjectInstance", "SubjectInstance")
                        .WithMany("ScheduledClasses")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubjectInstance");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.SubjectInstance", b =>
                {
                    b.HasOne("Rey.EQueue.Core.Entities.Subject", "Subject")
                        .WithMany("SubjectInstances")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.SubjectInstanceTeacher", b =>
                {
                    b.HasOne("Rey.EQueue.Core.Entities.SubjectInstance", "SubjectInstance")
                        .WithMany("SubjectInstanceTeachers")
                        .HasForeignKey("SubjectInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rey.EQueue.Core.Entities.Teacher", "Teacher")
                        .WithMany("SubjectInstanceTeachers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubjectInstance");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.Timetable", b =>
                {
                    b.HasOne("Rey.EQueue.Core.Entities.SubjectInstance", null)
                        .WithMany("Timetables")
                        .HasForeignKey("SubjectInstanceId");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.Queue", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.ScheduledClass", b =>
                {
                    b.Navigation("Queues");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.Subject", b =>
                {
                    b.Navigation("SubjectInstances");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.SubjectInstance", b =>
                {
                    b.Navigation("ScheduledClasses");

                    b.Navigation("SubjectInstanceTeachers");

                    b.Navigation("Timetables");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.Teacher", b =>
                {
                    b.Navigation("SubjectInstanceTeachers");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.Timetable", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Rey.EQueue.Core.Entities.User", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
